### ISSUE TITLE
Showing the dependency chain

### ISSUE THREAD

**Issue by pickfire** [danfuzz/blur#1]
Hi, even thought I haven't tried `blur` yet but I am interested to know if it can show the dependency chain.

By the way, is there any future plans to port it to C? And can it be ran parallely?

And I really hope that it could be used in POSIX shell to be more portable.

**Comment by danfuzz** [comment]
> Hi, even thought I haven't tried blur yet but I am interested to know if it can show the dependency chain.

You can tell it to `--dump` the ruleset which you can inspect for dependencies. Not sure if that's what you mean.

> By the way, is there any future plans to port it to C?

No. But if that's what you're looking for maybe you should look at Ninja <https://ninja-build.org/>, which is way more of a Real Product than this experiment.

> And can it be ran parallely?

Not right now it can't, but there's nothing in the design that rules that out as a future direction.

> And I really hope that it could be used in POSIX shell to be more portable.

I don't think POSIX `sh` is sufficiently expressive; I'd expect the resulting translation to be unpalatably difficult to read or maintain. I welcome hearing about any experimental results you might have in that endeavor.

**Comment by pickfire** [comment]
@danfuzz Ninja is very slow, you need to rewrite the ninja file everytime, I see no hope in ninja, I did a benchmark once. Speed: `make < mk < ninja < tup`.
